### ISSUE TITLE
Removing Bundled products

### ISSUE THREAD

**Issue by craftcmscoder** [webdna/cartbundle#2]
How can we remove bundled products ? I checked your controller but there was no action for the same.
Also Products aren't removing by craft commerce default method.

**Comment by nfourtythree** [comment]
Hi @craftcmscoder 

Firstly apologies for this not being in the wiki, it should probably been in there! The way to do this when looping through your cart is to check if it is a bundle and then use the `multiAdd/updateCart` action to nullify the quantities for those products.

The following template example should get you there:

```twig

{% set cartLineItems = cart.lineItems|cartBundle %}
{% for item in cartLineItems %}

  ...

  <form method="POST">
      <input type="hidden" name="action" value="multiAdd/updateCart">
      <input type="hidden" name="redirect" value="your-cart-url">
      {{ getCsrfInput() }}

      {% if item.options|length and item.options.bundleItems is defined and item.options.bundleItems|length %}
        {% for bundleItem in item.options.bundleItems %}
          <input type="hidden" size="4" name="items[{{ bundleItem.id }}][qty]" value="0">
        {% endfor %}
      {% else %}
        <input type="hidden" size="4" name="items[{{ item.id }}][qty]" value="0">
      {% endif %}

      <button type="submit" name="button">Remove</button>
  </form>

  ...
  
{% endfor %}


```

Hope this helps!
